Fix regression in #81
It seems #81 introduced some kind of bug:

I have the following rst file documenting MyClass object from ottemplate module:
```
.. currentmodule:: ottemplate

.. autosummary::
    :toctree: _generated/
    :template: class.rst_t

    MyClass
```

with class.rst_t:
```
{{ objname }}
{{ underline }}

.. currentmodule:: {{ module }}

.. autoclass:: {{ objname }}

   {% block methods %}
   .. automethod:: __init__
   {% endblock %}

```
results in the following error:
```
following exception was raised:
Traceback (most recent call last):
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named 'ottemplate.ottemplate.MyClass'; 'ottemplate.ottemplate' is not a package

```

What do you think @SirNO ?